name: Build Android APK

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        
    - name: Build Android APK
      run: |
        briefcase android build
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: password-generator-apk
        path: android/bin/*.apk
        
    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: android/bin/*.apk
