name: Build Android APK

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        
    - name: Build Android APK
      run: |
        briefcase android build
      
    - name: Upload APK to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: android/bin/*.apk
        asset_name: PasswordGenerator.apk
        tag: ${{ github.ref }}
Упрощенная версия (только сборка без артефактов):
yaml
name: Build Android APK

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        
    - name: Build Android APK
      run: |
        briefcase android build
        echo "APK собран в android/bin/"
        
    - name: List built files
      run: |
        ls -la android/bin/
